package com.alvarotc.bito.ui.habi

import android.content.Context
import android.media.AudioAttributes
import android.media.AudioManager
import android.media.SoundPool
import com.alvarotc.bito.R
import com.alvarotc.bito.data.settings.Settings
import com.alvarotc.bito.data.settings.SettingsRepository
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

/** Habi's four tiny cues (docs §5.3): a greeting, a celebration, a sad slide and a purchase pop. */
enum class HabiSound { GREETING, CELEBRATION, SAD, PURCHASE }

/**
 * Plays Habi's sounds — generated by `tools/habi_sounds.py`, never a third-party asset. Never
 * called from notification code (docs §5.3): the only callers are the Habi screen's stage tap,
 * a successful purchase, a logged relapse and the Today ring completing.
 *
 * [play] is fire-and-forget and non-suspend so every call site can invoke it inline: the gate
 * check and the actual playback both happen inside a coroutine it launches on its own scope,
 * reading the CURRENT [Settings] via [SettingsRepository.settings]'s `first()` each time rather
 * than trusting a value cached from some earlier collection. [shouldPlay] is split out as a pure,
 * directly-testable gate — [soundPool] is a private lazy field with no handle exposed outside this
 * class, so a test can't assert on it directly; keeping the actual gate logic pure and testable in
 * isolation is what makes that acceptable instead of a gap.
 */
class HabiSounds(
    private val context: Context,
    private val settings: SettingsRepository,
    // Overridable so tests can swap in a TestDispatcher and advanceUntilIdle() past `play`'s
    // launch instead of racing a real background thread.
    dispatcher: CoroutineDispatcher = Dispatchers.Default,
) {
    private val scope by lazy { CoroutineScope(SupervisorJob() + dispatcher) }

    private val soundPool: SoundPool by lazy {
        SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            )
            .build()
    }

    private val soundIds: Map<HabiSound, Int> by lazy {
        mapOf(
            HabiSound.GREETING to soundPool.load(context, R.raw.habi_meeh, 1),
            HabiSound.CELEBRATION to soundPool.load(context, R.raw.habi_cheer, 1),
            HabiSound.SAD to soundPool.load(context, R.raw.habi_sad, 1),
            HabiSound.PURCHASE to soundPool.load(context, R.raw.habi_pop, 1),
        )
    }

    private val audioManager: AudioManager? by lazy {
        context.getSystemService(Context.AUDIO_SERVICE) as? AudioManager
    }

    /** No-ops silently when Habi sounds are off in Ajustes, or the ringer isn't in normal mode. */
    fun play(sound: HabiSound) {
        scope.launch {
            if (!shouldPlay(settings.settings.first(), audioManager?.ringerMode)) return@launch
            val id = soundIds[sound] ?: return@launch
            soundPool.play(id, VOLUME, VOLUME, 1, 0, 1f)
        }
    }

    companion object {
        private const val MAX_STREAMS = 2
        private const val VOLUME = 1f

        /** Pure gate, unit-testable without a real [SoundPool] or [AudioManager]. */
        internal fun shouldPlay(
            settings: Settings,
            ringerMode: Int?,
        ): Boolean = settings.habiSoundsEnabled && ringerMode == AudioManager.RINGER_MODE_NORMAL
    }
}
