package com.alvarotc.bito.ui.habi

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import com.alvarotc.bito.R
import com.alvarotc.bito.data.settings.Settings
import com.alvarotc.bito.data.settings.SettingsRepository
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlin.random.Random

/** Habi's four tiny cues (docs §5.3): a greeting, a celebration, a sad slide and a purchase pop. */
enum class HabiSound { GREETING, CELEBRATION, SAD, PURCHASE, LOG }

/**
 * Plays Habi's sounds — generated by `tools/habi_sounds.py`, never a third-party asset. Never
 * called from notification code (docs §5.3): callers are the Habi screen's stage tap (GREETING),
 * successful purchase (PURCHASE), logged relapse (SAD), and celebration (CELEBRATION).
 *
 * Routed as `USAGE_GAME` / `CONTENT_TYPE_SONIFICATION` — architect ruling 2026-08-19, after QA
 * found the sounds silent on a Pixel in vibrate mode and expected them anyway: these cues follow
 * MEDIA volume, like a game, not the ringer. They play on vibrate/DND and are silenced only by
 * media volume 0 or the Ajustes toggle. This deliberately supersedes the functional doc's more
 * literal "respects silence/DND" wording for these four sounds specifically — the toggle plus
 * "never in notifications" (settings_habi_sounds_hint) is what actually holds.
 *
 * [play] is fire-and-forget and non-suspend so every call site can invoke it inline: the gate
 * check and the actual playback both happen inside a coroutine it launches on its own scope,
 * reading the CURRENT [Settings] via [SettingsRepository.settings]'s `first()` each time rather
 * than trusting a value cached from some earlier collection. [shouldPlay] is split out as a pure,
 * directly-testable gate — [soundPool] is a private field with no handle exposed outside this
 * class, so a test can't assert on it directly; keeping the actual gate logic pure and testable in
 * isolation is what makes that acceptable instead of a gap.
 *
 * [soundPool] and [soundIds] are built eagerly at construction, not lazily on first [play] — this
 * class is itself constructed once, eagerly, in `AppContainer` at app start, so preloading here
 * gives `SoundPool.load`'s async decode the whole time between app launch and the user's first tap
 * to finish. Deferring it to inside the first [play] call (the previous behavior) started the
 * decode and requested playback in the same instant, so the very first cue of a session was
 * frequently silent — `SoundPool.play` is a no-op for a sample whose decode hasn't completed yet.
 */
class HabiSounds(
    private val context: Context,
    private val settings: SettingsRepository,
    // Overridable so tests can swap in a TestDispatcher and advanceUntilIdle() past `play`'s
    // launch instead of racing a real background thread.
    dispatcher: CoroutineDispatcher = Dispatchers.Default,
) {
    private val scope by lazy { CoroutineScope(SupervisorJob() + dispatcher) }

    private val soundPool: SoundPool =
        SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            )
            .build()

    private val soundIds: Map<HabiSound, Int> =
        mapOf(
            HabiSound.GREETING to soundPool.load(context, R.raw.habi_meeh, 1),
            HabiSound.CELEBRATION to soundPool.load(context, R.raw.habi_cheer, 1),
            HabiSound.SAD to soundPool.load(context, R.raw.habi_sad, 1),
            HabiSound.PURCHASE to soundPool.load(context, R.raw.habi_pop, 1),
            HabiSound.LOG to soundPool.load(context, R.raw.log_tick, 1),
        )

    /** No-ops silently when Habi sounds are off in Ajustes — otherwise plays regardless of ringer mode. */
    fun play(sound: HabiSound) {
        scope.launch {
            if (!shouldPlay(settings.settings.first(), sound)) return@launch
            val id = soundIds[sound] ?: return@launch
            // Pitch varies a little per greeting so petting never sounds like the same sample on
            // repeat (QA 2026-08-23 — «que suene a mascota»).
            val rate = if (sound == HabiSound.GREETING) 0.94f + Random.nextFloat() * 0.12f else 1f
            soundPool.play(id, VOLUME, VOLUME, 1, 0, rate)
        }
    }

    companion object {
        private const val MAX_STREAMS = 2
        private const val VOLUME = 1f

        /** Pure gate, unit-testable without a real [SoundPool]. Ringer mode is deliberately not a factor (see class KDoc). LOG has its own Ajustes toggle — it is registro feedback, not Habi's voice. */
        internal fun shouldPlay(
            settings: Settings,
            sound: HabiSound,
        ): Boolean = if (sound == HabiSound.LOG) settings.logSoundEnabled else settings.habiSoundsEnabled
    }
}
