import type { CopyKey } from './es';

export const en: Record<CopyKey, string> = {
  frase: 'One tap. Done.',
  'descriptor.1': "A habit app that won't steal your time.",
  'descriptor.2': 'No accounts. No cloud. Not one line out to the internet.',
  'promesa.titular': "Logging that you did it shouldn't be another task.",
  'promesa.subtitulo': "Three ways to log it. Two don't even ask you to open the app.",
  'promesa.widget': 'From the home screen',
  'promesa.notificacion': 'From the notification',
  'promesa.repaso': 'In the evening review',
  'hace.rachas': "Streaks that don't punish.",
  'hace.logros': 'Real badges, real stats.',
  'habi.titular': "Habi's no decoration.",
  'nuevo.habi.voz.titular': 'Habi speaks in the voice you pick.',
  'habi.nota': 'You pick it at the start and change it anytime.',
  'voz.sargento.frase': "Acceptable. We both know you've got more.",
  'voz.sargento.def': 'Demands out of belief in you.',
  'voz.cheerleader.frase': 'Good week. And the next one? Even better!',
  'voz.cheerleader.def': 'Celebrates big, stays close on bad days.',
  'voz.neutra.frase': 'A steady week. Keep going.',
  'voz.neutra.def': 'States with precision, warm in a low voice.',
  'nuevo.tareas.titular': 'Not a habit? It fits too.',
  'nuevo.tareas.pie': 'Tasks, deadlines and a timer to get started.',
  'nuevo.respiracion.titular': 'When the day piles up, breathe.',
  'nuevo.respiracion.pie': 'Two minutes breathing with Habi. No points or streaks.',
  'nunca.titular': 'What Bito will never do',
  'nunca.palabra': 'Never',
  'nunca.1': 'ask for an account.',
  'nunca.2': 'upload your data to a cloud.',
  'nunca.3': 'have ads.',
  'cifra.gms': 'Google Play Services dependencies',
  'cifra.permisos': 'permissions of its own, no internet',
  'cifra.licencia': 'of the code, GPL-3.0-or-later',
  'cierre.titular': 'Start with one.',
  'nuevo.cierre.pie': 'Bito 1.3.0 · Android 8.0+ · Free software',
  'store.foco': 'Tasks, deadlines and a timer to get started.',
  'store.respiracion': 'Two minutes breathing with Habi.',
};
