import type { CopyKey } from './es';

export const en: Record<CopyKey, string> = {
  frase: 'One tap. Done.',
  'descriptor.1': "A habit app that won't steal your time.",
  'descriptor.2': 'No accounts. No cloud. Not one line out to the internet.',
  'promesa.titular': "Logging that you did it shouldn't be another task.",
  'promesa.subtitulo': "Three ways to log it. Two don't even ask you to open the app.",
  'promesa.widget': 'From the home screen',
  'promesa.notificacion': 'From the notification',
  'promesa.repaso': 'In the evening review',
  'hace.rachas': "Streaks that don't punish.",
  'hace.logros': 'Real badges, real stats.',
  'habi.titular': "Habi's no decoration.",
  'voz.sargento': "Acceptable. We both know you've got more.",
  habi_greeting_cheerleader_radiant: "You're on fire!",
  habi_sealed_neutra: "That's it. Rest.",
  'nuevo.tareas.titular': 'Not a habit? It fits too.',
  'nuevo.tareas.pie': 'Tasks, deadlines and a timer to get started.',
  'nunca.titular': 'What Bito will never do',
  'nunca.palabra': 'Never',
  'nunca.1': 'ask for an account.',
  'nunca.2': 'upload your data to a cloud.',
  'nunca.3': 'have ads.',
  'cifra.gms': 'Google Play Services dependencies',
  'cifra.permisos': 'permissions, none for internet',
  'cifra.licencia': 'of the code, GPL-3.0-or-later',
  'cierre.titular': 'Start with one.',
  'nuevo.cierre.pie': 'Bito 1.1.0 · Android 8.0+ · Free software',
};
