export const es = {
  frase: 'Un toque. Ya está.',
  'descriptor.1': 'La app de hábitos que no te roba tiempo.',
  'descriptor.2': 'Sin cuentas. Sin nube. Sin una sola línea que salga a internet.',
  'promesa.titular': 'Apuntar que lo has hecho no debería ser otra tarea.',
  'promesa.subtitulo': 'Tres maneras de registrar. Dos ni siquiera te piden abrir la app.',
  'promesa.widget': 'Desde la pantalla de inicio',
  'promesa.notificacion': 'Desde la notificación',
  'promesa.repaso': 'En el repaso de la noche',
  'hace.rachas': 'Rachas que no te castigan.',
  'hace.logros': 'Logros y estadísticas de verdad.',
  'habi.titular': 'Habi no es un adorno.',
  'voz.sargento': 'Aceptable. Tú y yo sabemos que puedes más.',
  habi_greeting_cheerleader_radiant: '¡Vas que vuelas!',
  habi_sealed_neutra: 'Ya está. Descansa.',
  'nuevo.tareas.titular': 'Y lo que no es un hábito, también cabe.',
  'nuevo.tareas.pie': 'Tareas, plazos y un temporizador para empezar.',
  'nunca.titular': 'Lo que Bito no va a hacer nunca',
  'nunca.palabra': 'Nunca',
  'nunca.1': 'te pedirá una cuenta.',
  'nunca.2': 'subirá tus datos a una nube.',
  'nunca.3': 'tendrá anuncios.',
  'cifra.gms': 'dependencias de Google Play Services',
  'cifra.permisos': 'permisos, y ninguno es internet',
  'cifra.licencia': 'del código bajo GPL-3.0-or-later',
  'cierre.titular': 'Empieza por uno.',
  'nuevo.cierre.pie': 'Bito 1.1.0 · Android 8.0+ · Software libre',
} as const;

export type CopyKey = keyof typeof es;
